// Generated by scripts/generate-strategy-registry.mjs. Do not edit.
import type { StrategyEngine } from "./types";
import engine1 from "./models/model1-blind-v3";
import engine2 from "./models/model1-blind";
import engine3 from "./models/model1";
import engine4 from "./models/model2-blind-v3";
import engine5 from "./models/model2-blind";
import engine6 from "./models/model2";

export const strategyEngines = {
  "model1-blind-v3": engine1,
  "model1-blind": engine2,
  "model1": engine3,
  "model2-blind-v3": engine4,
  "model2-blind": engine5,
  "model2": engine6,
} satisfies Record<string, StrategyEngine>;

for (const [id, engine] of Object.entries(strategyEngines)) {
  if (engine.id !== id) throw new Error(`Strategy model file ${id}.ts exports engine id ${engine.id}.`);
}
